import { ServiceItem } from '@/types';

export const DEFAULT_SERVICES: ServiceItem[] = [
    { id: 'agasalho', name: 'Agasalho de lã', priceLP: 45.00, priceP: 20.00 },
    { id: 'bermuda', name: 'Bermuda', priceLP: 25.00, priceP: 12.00 },
    { id: 'blazer', name: 'Blazer', priceLP: 50.00, priceP: 31.00 },
    { id: 'blusa', name: 'Blusa', priceLP: 30.00, priceP: 16.00 },
    { id: 'blusafina', name: 'Blusa Fina', priceLP: 30.00, priceP: 18.00 },
    { id: 'calca', name: 'Calça', priceLP: 25.00, priceP: 17.00 },
    { id: 'calcasocial', name: 'Calça Social', priceLP: 28.00, priceP: 18.00 },
    { id: 'camisa', name: 'Camisa', priceLP: 25.00, priceP: 17.00 },
    { id: 'camisapolo', name: 'Camisa Polo', priceLP: 25.00, priceP: 15.00 },
    { id: 'camisasocial', name: 'Camisa Social', priceLP: 30.00, priceP: 17.00 },
    { id: 'camiseta', name: 'Camiseta', priceLP: 25.00, priceP: 15.00 },
    { id: 'camisola', name: 'Camisola', priceLP: 30.00, priceP: 17.00 },
    { id: 'casaco', name: 'Casaco', priceLP: 50.00, priceP: 34.00 },
    { id: 'cueca', name: 'Cueca/Calcinha', priceLP: 12.00, priceP: null },
    { id: 'gravata', name: 'Gravata', priceLP: 20.00, priceP: 12.00 },
    { id: 'malha', name: 'Malha', priceLP: 28.00, priceP: 24.20 },
    { id: 'meias', name: 'Meias', priceLP: 12.00, priceP: null },
    { id: 'moletonblusa', name: 'Moletom (blusa)', priceLP: 38.00, priceP: 19.80 },
    { id: 'moletoncalca', name: 'Moletom (calça)', priceLP: 38.00, priceP: 19.80 },
    { id: 'paleto', name: 'Paletó', priceLP: 45.00, priceP: 42.00 },
    { id: 'pijama', name: 'Pijama', priceLP: 22.00, priceP: 18.00 },
    { id: 'robe', name: 'Robe', priceLP: 25.00, priceP: 20.00 },
    { id: 'roupao', name: 'Roupão', priceLP: 30.00, priceP: 20.00 },
    { id: 'saia', name: 'Saia', priceLP: 25.00, priceP: 19.00 },
    { id: 'saiafina', name: 'Saia Fina', priceLP: 25.00, priceP: 19.00 },
    { id: 'shorts', name: 'Shorts', priceLP: 25.00, priceP: 12.00 },
    { id: 'smoking', name: 'Smoking', priceLP: 60.00, priceP: 50.00 },
    { id: 'sobretudo', name: 'Sobretudo', priceLP: 70.00, priceP: 60.00 },
    { id: 'sutia', name: 'Sutiã', priceLP: 14.00, priceP: null },
    { id: 'tenis', name: 'Tênis', priceLP: 70.00, priceP: null },
    { id: 'terno', name: 'Terno', priceLP: 45.00, priceP: 42.00 },
    { id: 'vestido', name: 'Vestido', priceLP: 35.00, priceP: 30.00 },
    { id: 'vestidofino', name: 'Vestido Fino', priceLP: 50.00, priceP: null },
];
